# Generated by Django 5.1.6 on 2025-02-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlovha')),
                ('body', models.TextField(verbose_name='text')),
                ('photo', models.ImageField(upload_to='Media/news', verbose_name='Rasm')),
                ('created', models.DateTimeField(auto_now=True)),
                ('past_times', models.DateTimeField(auto_now_add=True, verbose_name='eski yangilik bolsa sanasi')),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/news')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.newsarticle')),
            ],
        ),
    ]
