# Generated by Django 5.2 on 2025-04-03 11:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulimUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('body', models.TextField(verbose_name='Malumot')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('qabul_day', models.CharField(blank=True, max_length=150, verbose_name='qabul kuni')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('photo', models.ImageField(upload_to='Bulim/')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='EkranImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='ekran_IMG/')),
            ],
            options={
                'verbose_name': 'Ekran Rasmi',
                'verbose_name_plural': 'Ekran Rasmlari',
            },
        ),
        migrations.CreateModel(
            name='ElonArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='vaziyat')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlovha')),
                ('body', models.TextField(verbose_name='text')),
                ('photo', models.ImageField(upload_to='news/', verbose_name='Rasm')),
                ('created', models.DateTimeField(auto_now=True)),
                ('past_times', models.DateTimeField(auto_now_add=True, verbose_name='eski yangilik bolsa sanasi')),
                ('views', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Elon',
                'verbose_name_plural': 'Elonlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FacultetUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('body', models.TextField(verbose_name='Malumot')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('qabul_day', models.CharField(blank=True, max_length=150, verbose_name='qabul kuni')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('photo', models.ImageField(upload_to='Fakultet/')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
            },
        ),
        migrations.CreateModel(
            name='HavolaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='Havola-img/')),
                ('link', models.CharField(max_length=250, verbose_name='havola linki')),
            ],
            options={
                'verbose_name': 'Foydali havola',
                'verbose_name_plural': 'Foydali havola',
            },
        ),
        migrations.CreateModel(
            name='KafedraUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('body', models.TextField(verbose_name='Malumot')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('qabul_day', models.CharField(blank=True, max_length=150, verbose_name='qabul kuni')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('photo', models.ImageField(upload_to='Kafedra/')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedra',
            },
        ),
        migrations.CreateModel(
            name='MarkazUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('body', models.TextField(verbose_name='Malumot')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('qabul_day', models.CharField(blank=True, max_length=150, verbose_name='qabul kuni')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('photo', models.ImageField(upload_to='Markaz/')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Markaz',
                'verbose_name_plural': 'Markazlar',
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlovha')),
                ('body', models.TextField(verbose_name='text')),
                ('photo', models.ImageField(upload_to='news', verbose_name='Rasm')),
                ('created', models.DateTimeField(auto_now=True)),
                ('past_times', models.DateTimeField(blank=True, verbose_name='eski yangilik bolsa sanasi')),
                ('views', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RektoratCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Universitet Kategorya',
                'verbose_name_plural': 'Universitet Kategorya',
            },
        ),
        migrations.CreateModel(
            name='BulimInUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('photo', models.ImageField(upload_to='Bulim/')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('tg', models.CharField(max_length=150, verbose_name='tg manzil')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bulimusermodel')),
            ],
            options={
                'verbose_name': "Bo'lim ichki Hodimlar",
                'verbose_name_plural': "Bo'lim ichki Hodimlar",
            },
        ),
        migrations.CreateModel(
            name='ElonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Elon/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.elonarticle')),
            ],
        ),
        migrations.CreateModel(
            name='FacultetInUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('photo', models.ImageField(upload_to='Fakultet/')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('tg', models.CharField(max_length=150, verbose_name='tg manzil')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facultetusermodel')),
            ],
            options={
                'verbose_name': 'Fakultet ichki Hodimlar',
                'verbose_name_plural': 'Fakultet ichki Hodimlar',
            },
        ),
        migrations.CreateModel(
            name='KafedraInUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('photo', models.ImageField(upload_to='Kafedra/')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('tg', models.CharField(max_length=150, verbose_name='tg manzil')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.kafedrausermodel')),
            ],
            options={
                'verbose_name': 'Kafedra ichki Hodimlar',
                'verbose_name_plural': 'Kafedra ichki Hodimlar',
            },
        ),
        migrations.CreateModel(
            name='MarkazInUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('photo', models.ImageField(upload_to='Markaz/')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('tg', models.CharField(max_length=150, verbose_name='tg manzil')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.markazusermodel')),
            ],
            options={
                'verbose_name': 'Markaz ichki Hodimlar',
                'verbose_name_plural': 'Markaz ichki Hodimlar',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.newsarticle')),
            ],
        ),
        migrations.CreateModel(
            name='RectoratUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('body', models.TextField(verbose_name='Malumot')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('qabul_day', models.CharField(blank=True, max_length=150, verbose_name='qabul kuni')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('photo', models.ImageField(upload_to='Rektorat/')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rektoratcategory')),
            ],
            options={
                'verbose_name': 'Rektorat Hodimlar',
                'verbose_name_plural': 'Rektorat Hodimlar',
            },
        ),
        migrations.AddField(
            model_name='markazusermodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rektoratcategory'),
        ),
        migrations.AddField(
            model_name='kafedrausermodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rektoratcategory'),
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rektoratcategory'),
        ),
        migrations.AddField(
            model_name='bulimusermodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rektoratcategory'),
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('photo', models.ImageField(upload_to='Rektorat/')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('tg', models.CharField(max_length=150, verbose_name='tg manzil')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rectoratusermodel')),
            ],
            options={
                'verbose_name': 'Rektorat ichki Hodimlar',
                'verbose_name_plural': 'Rektorat ichki Hodimlar',
            },
        ),
    ]
