# Generated by Django 5.1.6 on 2025-02-20 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkranImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='Media/ekran_IMG/')),
            ],
            options={
                'verbose_name': 'Ekran Rasmi',
                'verbose_name_plural': 'Ekran Rasmlari',
            },
        ),
        migrations.CreateModel(
            name='ElonArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='vaziyat')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlovha')),
                ('body', models.TextField(verbose_name='text')),
                ('photo', models.ImageField(upload_to='Media/news', verbose_name='Rasm')),
                ('created', models.DateTimeField(auto_now=True)),
                ('past_times', models.DateTimeField(auto_now_add=True, verbose_name='eski yangilik bolsa sanasi')),
                ('views', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Elon',
                'verbose_name_plural': 'Elonlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HavolaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='Media/FH/')),
                ('link', models.CharField(max_length=250, verbose_name='havola linki')),
            ],
            options={
                'verbose_name': 'Foydali havola',
                'verbose_name_plural': 'Foydali havola',
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(default='news', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ElonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/news')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.elonarticle')),
            ],
        ),
    ]
