# Generated by Django 5.2 on 2025-04-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elonarticle',
            name='body_en',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='elonarticle',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='elonarticle',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='elonarticle',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='vaziyat'),
        ),
        migrations.AddField(
            model_name='elonarticle',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='vaziyat'),
        ),
        migrations.AddField(
            model_name='elonarticle',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='vaziyat'),
        ),
        migrations.AddField(
            model_name='elonarticle',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlovha'),
        ),
        migrations.AddField(
            model_name='elonarticle',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlovha'),
        ),
        migrations.AddField(
            model_name='elonarticle',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlovha'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='body_en',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlovha'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlovha'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlovha'),
        ),
    ]
