# Generated by Django 5.1.6 on 2025-02-21 10:52

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ekranimages_elonarticle_havolaimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RektoratCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Universitet Kategorya',
                'verbose_name_plural': 'Universitet Kategorya',
            },
        ),
        migrations.AlterField(
            model_name='elonarticle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='past_times',
            field=models.DateTimeField(blank=True, verbose_name='eski yangilik bolsa sanasi'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='RectoratUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('body', models.TextField(verbose_name='Malumot')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rektoratcategory')),
            ],
            options={
                'verbose_name': 'Rektorat Hodimlar',
                'verbose_name_plural': 'Rektorat Hodimlar',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('tg', models.CharField(max_length=150, verbose_name='tg manzil')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rectoratusermodel')),
            ],
            options={
                'verbose_name': 'Rektorat Hodimlar',
                'verbose_name_plural': 'Rektorat Hodimlar',
            },
        ),
    ]
