# Generated by Django 5.2 on 2025-04-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_elonarticle_body_en_elonarticle_body_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buliminusermodel',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='buliminusermodel',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='buliminusermodel',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='buliminusermodel',
            name='rang_en',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='buliminusermodel',
            name='rang_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='buliminusermodel',
            name='rang_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='buliminusermodel',
            name='tg_en',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='buliminusermodel',
            name='tg_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='buliminusermodel',
            name='tg_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='bulimusermodel',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='bulimusermodel',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='bulimusermodel',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='bulimusermodel',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='bulimusermodel',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='bulimusermodel',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='bulimusermodel',
            name='qabul_day_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='bulimusermodel',
            name='qabul_day_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='bulimusermodel',
            name='qabul_day_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='bulimusermodel',
            name='rang_en',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='bulimusermodel',
            name='rang_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='bulimusermodel',
            name='rang_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='facultetinusermodel',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='facultetinusermodel',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='facultetinusermodel',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='facultetinusermodel',
            name='rang_en',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='facultetinusermodel',
            name='rang_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='facultetinusermodel',
            name='rang_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='facultetinusermodel',
            name='tg_en',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='facultetinusermodel',
            name='tg_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='facultetinusermodel',
            name='tg_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='qabul_day_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='qabul_day_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='qabul_day_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='rang_en',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='rang_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='rang_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='havolaimages',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='havolaimages',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='havolaimages',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kafedrainusermodel',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='kafedrainusermodel',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='kafedrainusermodel',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='kafedrainusermodel',
            name='rang_en',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='kafedrainusermodel',
            name='rang_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='kafedrainusermodel',
            name='rang_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='kafedrainusermodel',
            name='tg_en',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='kafedrainusermodel',
            name='tg_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='kafedrainusermodel',
            name='tg_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='kafedrausermodel',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='kafedrausermodel',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='kafedrausermodel',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='kafedrausermodel',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='kafedrausermodel',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='kafedrausermodel',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='kafedrausermodel',
            name='qabul_day_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='kafedrausermodel',
            name='qabul_day_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='kafedrausermodel',
            name='qabul_day_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='kafedrausermodel',
            name='rang_en',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='kafedrausermodel',
            name='rang_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='kafedrausermodel',
            name='rang_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='markazinusermodel',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='markazinusermodel',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='markazinusermodel',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='markazinusermodel',
            name='rang_en',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='markazinusermodel',
            name='rang_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='markazinusermodel',
            name='rang_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='markazinusermodel',
            name='tg_en',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='markazinusermodel',
            name='tg_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='markazinusermodel',
            name='tg_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='markazusermodel',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='markazusermodel',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='markazusermodel',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='markazusermodel',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='markazusermodel',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='markazusermodel',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='markazusermodel',
            name='qabul_day_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='markazusermodel',
            name='qabul_day_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='markazusermodel',
            name='qabul_day_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='markazusermodel',
            name='rang_en',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='markazusermodel',
            name='rang_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='markazusermodel',
            name='rang_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='rectoratusermodel',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='rectoratusermodel',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='rectoratusermodel',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='Malumot'),
        ),
        migrations.AddField(
            model_name='rectoratusermodel',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='rectoratusermodel',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='rectoratusermodel',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='rectoratusermodel',
            name='qabul_day_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='rectoratusermodel',
            name='qabul_day_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='rectoratusermodel',
            name='qabul_day_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='qabul kuni'),
        ),
        migrations.AddField(
            model_name='rectoratusermodel',
            name='rang_en',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='rectoratusermodel',
            name='rang_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='rectoratusermodel',
            name='rang_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='rektoratcategory',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='rektoratcategory',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='rektoratcategory',
            name='name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='rang_en',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='rang_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='rang_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='lavozim'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='tg_en',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='tg_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='tg_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='tg manzil'),
        ),
    ]
