# Generated by Django 5.2 on 2025-04-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_buliminusermodel_name_en_buliminusermodel_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rektoratcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='rektoratcategory',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='rektoratcategory',
            name='name_uz',
        ),
    ]
