# Generated by Django 5.1.6 on 2025-02-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rektoratcategory_alter_elonarticle_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectoratusermodel',
            name='photo',
            field=models.ImageField(default='1', upload_to='Media/Rektorat/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(default='1.jpg', upload_to='Media/Rektorat/'),
            preserve_default=False,
        ),
    ]
