# Generated by Django 5.1.6 on 2025-02-22 04:25

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_usermodel_options_facultetusermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultetusermodel',
            options={'verbose_name': 'Fakultet', 'verbose_name_plural': 'Fakultetlar'},
        ),
        migrations.RemoveField(
            model_name='facultetusermodel',
            name='tg',
        ),
        migrations.AddField(
            model_name='facultetusermodel',
            name='body',
            field=models.TextField(default='sas', verbose_name='Malumot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facultetusermodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rektoratcategory'),
        ),
        migrations.CreateModel(
            name='FacultetInUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('photo', models.ImageField(upload_to='Media/Fakultet/')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('tg', models.CharField(max_length=150, verbose_name='tg manzil')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rectoratusermodel')),
            ],
            options={
                'verbose_name': 'Fakultet ichki Hodimlar',
                'verbose_name_plural': 'Fakultet ichki Hodimlar',
            },
        ),
    ]
