# Generated by Django 5.2 on 2025-05-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uiversitet_Struktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('video_file', models.FileField(upload_to='struktura/')),
            ],
        ),
    ]
