# Generated by Django 5.1.6 on 2025-02-22 05:41

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_facultetusermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultetinusermodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facultetusermodel'),
        ),
        migrations.CreateModel(
            name='BulimUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('body', models.TextField(verbose_name='Malumot')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('photo', models.ImageField(upload_to='Media/Bulim/')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rektoratcategory')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='BulimInUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('photo', models.ImageField(upload_to='Media/Bulim/')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('tg', models.CharField(max_length=150, verbose_name='tg manzil')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bulimusermodel')),
            ],
            options={
                'verbose_name': "Bo'lim ichki Hodimlar",
                'verbose_name_plural': "Bo'lim ichki Hodimlar",
            },
        ),
        migrations.CreateModel(
            name='KafedraInUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('photo', models.ImageField(upload_to='Media/Kafedra/')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('tg', models.CharField(max_length=150, verbose_name='tg manzil')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bulimusermodel')),
            ],
            options={
                'verbose_name': 'Kafedra ichki Hodimlar',
                'verbose_name_plural': 'Kafedra ichki Hodimlar',
            },
        ),
        migrations.CreateModel(
            name='KafedraUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('body', models.TextField(verbose_name='Malumot')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('photo', models.ImageField(upload_to='Media/Kafedra/')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rektoratcategory')),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedra',
            },
        ),
        migrations.CreateModel(
            name='MarkazUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('body', models.TextField(verbose_name='Malumot')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('photo', models.ImageField(upload_to='Media/markaz/')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rektoratcategory')),
            ],
            options={
                'verbose_name': 'Markaz',
                'verbose_name_plural': 'Markazlar',
            },
        ),
        migrations.CreateModel(
            name='MarkazInUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('rang', models.CharField(max_length=150, verbose_name='lavozim')),
                ('photo', models.ImageField(upload_to='Media/Markaz/')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tell number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('tg', models.CharField(max_length=150, verbose_name='tg manzil')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.markazusermodel')),
            ],
            options={
                'verbose_name': 'Markaz ichki Hodimlar',
                'verbose_name_plural': 'Markaz ichki Hodimlar',
            },
        ),
    ]
