# Generated by Django 5.1.6 on 2025-03-17 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_facultetinusermodel_category_bulimusermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafedrainusermodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.kafedrausermodel'),
        ),
    ]
