# Generated by Django 5.2 on 2025-05-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_uiversitet_struktura'),
    ]

    operations = [
        migrations.CreateModel(
            name='galareyaIMG1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('img', models.FileField(upload_to='galareya/')),
            ],
            options={
                'verbose_name': 'Galareya rasmi-1',
                'verbose_name_plural': 'Galareya rasmi-1',
            },
        ),
        migrations.CreateModel(
            name='galareyaIMG2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('img', models.FileField(upload_to='galareya/')),
            ],
            options={
                'verbose_name': 'Galareya rasmi-2',
                'verbose_name_plural': 'Galareya rasmi-2',
            },
        ),
        migrations.CreateModel(
            name='galareyaIMG3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('img', models.FileField(upload_to='galareya/')),
            ],
            options={
                'verbose_name': 'Galareya rasmi-3',
                'verbose_name_plural': 'Galareya rasmi-3',
            },
        ),
        migrations.CreateModel(
            name='galareyaIMG4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('img', models.FileField(upload_to='galareya/')),
            ],
            options={
                'verbose_name': 'Galareya rasmi-4',
                'verbose_name_plural': 'Galareya rasmi-4',
            },
        ),
    ]
